#include "../guppy.h"

// int main() {
//     GupArena a = gup_arena_create();

//     char html_file_path[32];
//     char css_actual_file_path[32];
//     char css_expected_file_path[32];
//     char test_command[128];
//     int test_num = 1;

//     sprintf(html_file_path, "./tests/test%d.html", test_num);
//     sprintf(css_actual_file_path, "./tests/test%d_actual.css", test_num);
//     sprintf(css_expected_file_path, "./tests/test%d_expected.css", test_num);

//     system("make -B -s");
//     while (gup_file_exists(html_file_path)) {
//         sprintf(test_command, "./taillight %s %s", html_file_path, css_actual_file_path);

//         printf("Test %d...", test_num);
//         system(test_command);

//         gup_assert_verbose(gup_file_exists(css_actual_file_path), "Taillight didn't actually produce an output css file.");
        
//         GupString expected;
//         gup_assert(gup_file_read((GupAllocator *)&a, css_expected_file_path, &expected));
//         GupString actual;
//         gup_assert(gup_file_read((GupAllocator *)&a, css_actual_file_path, &actual));
//         gup_assert_verbose(gup_string_equals(expected, actual), "The output css didn't match the expected!");

//         printf("PASS\n");
//         test_num++;
//         sprintf(html_file_path, "./tests/test%d.html", test_num);
//         sprintf(css_actual_file_path, "./tests/test%d_actual.css", test_num);
//         sprintf(css_expected_file_path, "./tests/test%d_expected.css", test_num);

//         gup_arena_free(&a);
//     }

//     printf("All tests passed!\n");
//     gup_arena_destroy(&a);
//     return 0;
// }

int main() {
    GupArena a = gup_arena_create();

    system("make -B -s");
    system("./taillight tests/test1.html tests/test1_actual.css");

    GupString test_file_1_contents;
    gup_assert_verbose(gup_file_read((GupAllocator *)&a, "tests/test1_actual.css", &test_file_1_contents), "Was unable to open test1_actual.css");

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/**"                                                                                                                                  "\n"
            " * Stylesheet generated by taillight https://github.com/cbouwense/taillight."                                                         "\n"
            " * You can edit this file, but I would not recommend it since it will be overwritten without warning the next time you run taillight.""\n"
            " * If you want to add your own rules, I recommend you add them to a separate stylesheet (I use a 'custom.css' file for this)."        "\n"
            " */"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".w-100\\% {"   "\n"
            "  width: 100%;""\n"
            "}"             "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".gap-1rem {" "\n"
            "  gap: 1rem;""\n"
            "}"           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".flex {"         "\n"
            "  display: flex;""\n"
            "}"               "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".bg-\\#dd0000 {"             "\n"
            "  background-color: #dd0000;""\n"
            "}"                           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".bg-\\#dd0000 {"             "\n"
            "  background-color: #dd0000;""\n"
            "}"                           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/* Mobile */"                     "\n"
            "@media (max-width: 768px) {"      "\n"
            "  .mobile { display: inherit; }""\n"
            "  .tablet { display: none; }"   "\n"
            "  .computer { display: none; }" "\n"
            "  .ultrawide { display: none; }""\n"
            "  :root { font-size: 14px; }"   "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "  .m\\:w-75\\% {""\n"
            "    width: 75%;" "\n"
            "  }"             "\n"
        )
    );

    gup_arena_destroy(&a);
    return 0;
}
