#include "../guppy.h"

void test1() {
    GupArena a = gup_arena_create();

    system("make -B -s");
    system("./taillight tests/test1.html tests/test1_actual.css");

    GupString test_file_1_contents;
    gup_assert_verbose(gup_file_read((GupAllocator *)&a, "tests/test1_actual.css", &test_file_1_contents), "Was unable to open test1_actual.css");

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/**"                                                                                                                                  "\n"
            " * Stylesheet generated by taillight https://github.com/cbouwense/taillight."                                                         "\n"
            " * You can edit this file, but I would not recommend it since it will be overwritten without warning the next time you run taillight.""\n"
            " * If you want to add your own rules, I recommend you add them to a separate stylesheet (I use a 'custom.css' file for this)."        "\n"
            " */"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".w-100\\% {"   "\n"
            "  width: 100%;""\n"
            "}"             "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".gap-1rem {" "\n"
            "  gap: 1rem;""\n"
            "}"           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".flex {"         "\n"
            "  display: flex;""\n"
            "}"               "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            ".bg-\\#dd0000 {"             "\n"
            "  background-color: #dd0000;""\n"
            "}"                           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/* Mobile */"                   "\n"
            "@media (max-width: 768px) {"    "\n"
            "  .mobile { display: inherit; }""\n"
            "  .tablet { display: none; }"   "\n"
            "  .computer { display: none; }" "\n"
            "  .ultrawide { display: none; }""\n"
            "  :root { font-size: 14px; }"   "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "  .m\\:w-75\\% {""\n"
            "    width: 75%;" "\n"
            "  }"             "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/* Tablet */"                                       "\n"
            "@media (min-width: 768px) and (max-width: 1024px) {""\n"
            "  .mobile { display: none; }"                       "\n"
            "  .tablet { display: inherit; }"                    "\n"
            "  .computer { display: none; }"                     "\n"
            "  .ultrawide { display: none; }"                    "\n"
            "  :root { font-size: 14px; }"                       "\n"
            "}"                                                  "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/* Computer (desktop / laptop) */"                   "\n"
            "@media (min-width: 1024px) and (max-width: 3840px) {""\n"
            "  .mobile { display: none; }"                        "\n"
            "  .tablet { display: none; }"                        "\n"
            "  .computer { display: inherit; }"                   "\n"
            "  .ultrawide { display: none; }"                     "\n"
            "  :root { font-size: 18px; }"                        "\n"
            "}"                                                   "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_1_contents,
            "/* Ultrawide */"                   "\n"
            "@media (min-width: 3840px) {"      "\n"
            "  .mobile { display: none; }"      "\n"
            "  .tablet { display: none; }"      "\n"
            "  .computer { display: none; }"    "\n"
            "  .ultrawide { display: inherit; }""\n"
            "  :root { font-size: 18px; }"      "\n"
        )
    );

    gup_arena_destroy(&a);
}

void test2() {
    GupArena a = gup_arena_create();

    system("./taillight tests/test2.html tests/test2_actual.css");

    GupString test_file_2_contents;
    gup_assert_verbose(gup_file_read((GupAllocator *)&a, "tests/test2_actual.css", &test_file_2_contents), "Was unable to open test2_actual.css");

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            "/**"                                                                                                                                  "\n"
            " * Stylesheet generated by taillight https://github.com/cbouwense/taillight."                                                         "\n"
            " * You can edit this file, but I would not recommend it since it will be overwritten without warning the next time you run taillight.""\n"
            " * If you want to add your own rules, I recommend you add them to a separate stylesheet (I use a 'custom.css' file for this)."        "\n"
            " */"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".w-100\\% {"   "\n"
            "  width: 100%;""\n"
            "}"             "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".pt-2rem {"          "\n"
            "  padding-top: 2rem;""\n"
            "}"                   "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".alignCenter {"        "\n"
            "  align-items: center;""\n"
            "}"                     "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".bg-\\#bababa {"             "\n"
            "  background-color: #bababa;""\n"
            "}"                           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".h-100\\% {"    "\n"
            "  height: 100%;""\n"
            "}"              "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".b-double-green {"      "\n"
            "  border: double green;""\n"
            "}"                      "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".column {"                "\n"
            "  flex-direction: column;""\n"
            "}"                        "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".h-10vh {"      "\n"
            "  height: 10vh;""\n"
            "}"              "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".b-solid {"      "\n"
            "  border: solid;""\n"
            "}"               "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".gap-1rem {" "\n"
            "  gap: 1rem;""\n"
            "}"           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".flex {"         "\n"
            "  display: flex;""\n"
            "}"               "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".b-6px-red-dotted {"      "\n"
            "  border: 6px red dotted;""\n"
            "}"                        "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".bg-\\#eeeeee {"             "\n"
            "  background-color: #eeeeee;""\n"
            "}"                           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".w-75\\% {"   "\n"
            "  width: 75%;""\n"
            "}"            "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".breakAll {"             "\n"
            "  word-break: break-all;""\n"
            "}"                       "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".light-shadow {"                                   "\n"
            "  box-shadow: 0 0 16px 0 rgba(255, 255, 255, 0.2);""\n"
            "}"                                                 "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".p-0\\.5rem {"     "\n"
            "  padding: 0.5rem;""\n"
            "}"                 "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".gap-2rem {" "\n"
            "  gap: 2rem;""\n"
            "}"           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".brad-0\\.25rem {"        "\n"
            "  border-radius: 0.25rem;""\n"
            "}"                        "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".w-100\\%\\! {"           "\n"
            "  width: 100% !important;""\n"
            "}"                        "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            ".b-1px-solid-\\#bababa {"    "\n"
            "  border: 1px solid #bababa;""\n"
            "}"                           "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            "/* Mobile */"                   "\n"
            "@media (max-width: 768px) {"    "\n"
            "  .mobile { display: inherit; }""\n"
            "  .tablet { display: none; }"   "\n"
            "  .computer { display: none; }" "\n"
            "  .ultrawide { display: none; }""\n"
            "  :root { font-size: 14px; }"   "\n"
            "}"                              "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            "/* Tablet */"                                       "\n"
            "@media (min-width: 768px) and (max-width: 1024px) {""\n"
            "  .mobile { display: none; }"                       "\n"
            "  .tablet { display: inherit; }"                    "\n"
            "  .computer { display: none; }"                     "\n"
            "  .ultrawide { display: none; }"                    "\n"
            "  :root { font-size: 14px; }"                       "\n"
            "}"                                                  "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            "/* Computer (desktop / laptop) */"                   "\n"
            "@media (min-width: 1024px) and (max-width: 3840px) {""\n"
            "  .mobile { display: none; }"                        "\n"
            "  .tablet { display: none; }"                        "\n"
            "  .computer { display: inherit; }"                   "\n"
            "  .ultrawide { display: none; }"                     "\n"
            "  :root { font-size: 18px; }"                        "\n"
            "}"                                                   "\n"
        )
    );

    gup_assert(
        gup_string_contains_cstr(test_file_2_contents,
            "/* Ultrawide */"                   "\n"
            "@media (min-width: 3840px) {"      "\n"
            "  .mobile { display: none; }"      "\n"
            "  .tablet { display: none; }"      "\n"
            "  .computer { display: none; }"    "\n"
            "  .ultrawide { display: inherit; }""\n"
            "  :root { font-size: 18px; }"      "\n"
            "}"                                 "\n"
        )
    );

    gup_arena_destroy(&a);
}

int main(void) {
    printf("Rebuilding taillight from scratch...");
    system("make -s -B");
    printf("DONE\n");

    printf("Test 1...");
    test1();
    printf("PASS\n");

    printf("Test 2...");
    test2();
    printf("PASS\n");

    return 0;
}
